/**
 * contains a list of commands. you can link and unlink any command you like
 */
module.exports = {
    "ping": "ping",
    "hello": "hello",
    "lock": "lock",
    "stats": "stats",
    "add": "add",
    "remove": "remove",
    "unlock": "unlock",
    "info": "info",
    "hash": "hash",
    "bf2": "bf2",
    "alphakey": "alphakey",
    "bf2142": "bf2142",
    "link": "link",
    "refresh": "refresh",
    "yo": "yo",
    "cookie": "cookie",
    "request": "request",
    "status": "status",
    "quote": "quote",
    "q":"quote",
   // "emojify": "emojify",
    "emoji": "emoji",
    "e":"emoji",
    "http": "http",
    "8ball": "8ball",
    "slowmov": "slowmov",
    "whoisplaying": "whoisplaying",
    "say": "say",
    "delete": "delete",
    "exec": "exec",
    "query": "query",
    "cmute": "cmute",
    "cunmute": "cunmute",
    "cm":"cmute",
    "cum":"cunmute",
    "m":"mute",
    "um":"unmute",
    "mute": "mute",
    "fun": "fun",
    "unmute": "unmute",
    "mute": "mute",
    "unmute": "unmute",
    "dj": "dj",
    "hi": "hello",
    "access_log": "access_log",
    "al":"access_log"
    //"game": "game"
}
